### ISSUE TITLE
UAF 1.0 metadata test

### ISSUE THREAD

**Issue by jenkay** [fido-alliance/conformance-tool-issues#10]
Tool indicates a failure for metadata-stmt-1 ; however the test case doesn't match with the spec.

Test case is for aaid: Section 4.1

Looks like the tool is not corresponding to the right test case.

```
1) 

        Metadata-Stmt-1

        Verify compliance of metadata statement fields.

     P-1
        Required aaid, of type AAID.
            MUST be in format of {2 byte encoded in HEX}#{2 byte encoded in HEX}, e.g. FFFF#FC01
    :
     AssertionError: aaid 4e4e#4010 is not in format {2 byte encoded in HEX}#{2 byte encoded in HEX}!: expected '4e4e#4010' to match /^[A-F0-9]{4}#[A-F0-9]{4}$/
      at n.eval (eval at compileCode (assets/scripts/sandbox.js:23:26), <anonymous>:4487:16)
      at r (assets/scripts/vendor/mocha.min.js:1:40757)
      at r.run (assets/scripts/vendor/mocha.min.js:1:41838)
      at i.runTest (assets/scripts/vendor/mocha.min.js:1:46569)
      at assets/scripts/vendor/mocha.min.js:1:47206
      at r (assets/scripts/vendor/mocha.min.js:1:45957)
      at assets/scripts/vendor/mocha.min.js:1:46026
      at n (assets/scripts/vendor/mocha.min.js:1:45394)
      at assets/scripts/vendor/mocha.min.js:1:45868
      at i (assets/scripts/vendor/mocha.min.js:1:571)
```

**Comment by herrjemand** [comment]
Resolved in v0.9.10

**Comment by jenkay** [comment]
@herrjemand
Sorry. I failed to mention I am testing with 0.9.12

**Comment by herrjemand** [comment]
@jenkay Is this still an issues in 0.9.12?

**Comment by herrjemand** [comment]
@jenkay or you mean the android app?

**Comment by herrjemand** [comment]
@jenka updated Android build: v0.8.14 should resolve your issue
