### ISSUE TITLE
UAF 1.1 Protocol-Auth-Resp-3

### ISSUE THREAD

**Issue by k-tono** [fido-alliance/conformance-tool-issues#100]
Still reproducible on Tool Version 0.8.36

```
TypeError: Cannot read property 'assertions' of undefined
    at getTestStaticJSON.then.then (eval at compileCode (assets/scripts/sandbox.js:23:26), &lt;anonymous&gt;:10068:83)
    at t.invoke (build/polyfills.js:3:11562)
    at n.run (build/polyfills.js:3:6468)
    at build/polyfills.js:3:3767
    at t.invokeTask (build/polyfills.js:3:12256)
    at n.runTask (build/polyfills.js:3:7153)
    at a (build/polyfills.js:3:2312)
    at &lt;anonymous&gt;
```

**Comment by herrjemand** [comment]
Resolved. Ref #99
