### ISSUE TITLE
UAF 1.1 Protocol-Auth/Dereg-Req-4 BeforeHook fails

### ISSUE THREAD

**Issue by k-tono** [fido-alliance/conformance-tool-issues#105]
Tool Version 0.8.38

Error: Error while fetching AuthToken. Mesage is: TypeError: Failed to fetch
    at d (build/polyfills.js:3:3991)
    at window.fetch.then.then.catch (eval at compileCode (assets/scripts/sandbox.js:23:26), <anonymous>:72:15)
    at t.invoke (build/polyfills.js:3:11562)
    at n.run (build/polyfills.js:3:6468)
    at build/polyfills.js:3:3767
    at t.invokeTask (build/polyfills.js:3:12256)
    at n.runTask (build/polyfills.js:3:7153)
    at a (build/polyfills.js:3:2312)

**Comment by herrjemand** [comment]
This issue suppose to be resolved in v0.8.39. But I am getting untrusted facet. I am uploading build in the next few hours. Sorry for the delay.

**Comment by herrjemand** [comment]
Fails because of #96
