### ISSUE TITLE
FC-API Tests Failing

### ISSUE THREAD

**Issue by mlourie** [fido-alliance/conformance-tool-issues#113]
This is on a Pixel

FC-API-Android-1 P-1 (FAILED)

Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
    at new d (build/polyfills.js:3:3991)
    at assets/scripts/vendor/mocha.min.js:1:40022

FC-API-Android-1 P-3 (FAILED)

Error: [object ErrorEvent] (undefined:undefined)
    at new d (build/polyfills.js:3:3991)
    at uncaughtException.r.onerror (assets/scripts/vendor/mocha.min.js:1:982)
    at n (build/polyfills.js:2:27433)

**Comment by herrjemand** [comment]
Resolved in v0.8.44
