### ISSUE TITLE
UAF 1.1 - Server-Dereg-Req-2 P-2 Typo in test code

### ISSUE THREAD

**Issue by vens1** [fido-alliance/conformance-tool-issues#50]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.18

## Issue description
Tool fails in Server-Dereg-Req-2 P-1:
```
P-1 DeregistrationRequest MUST contain "header" field, of type Dictionary ‣
TypeError: Cannot read property 'header' of undefined
    at r.it (eval at compileCode (js/sandbox.js:25:26), <anonymous>:5113:44)
    at r (js/vendor/mocha.min.js:1:40757)
    at r.run (js/vendor/mocha.min.js:1:41838)
    at i.runTest (js/vendor/mocha.min.js:1:46569)
    at js/vendor/mocha.min.js:1:47206
    at r (js/vendor/mocha.min.js:1:45957)
    at js/vendor/mocha.min.js:1:46026
    at n (js/vendor/mocha.min.js:1:45394)
    at js/vendor/mocha.min.js:1:45868
    at i (js/vendor/mocha.min.js:1:571)
```
Tool fails in Server-Dereg-Req-2 P-2:
```
TypeError: Cannot read property 'authenticators' of undefined
    at r.it (eval at compileCode (js/sandbox.js:25:26), <anonymous>:5068:43)
    at r (js/vendor/mocha.min.js:1:40757)
    at r.run (js/vendor/mocha.min.js:1:41838)
    at i.runTest (js/vendor/mocha.min.js:1:46569)
    at js/vendor/mocha.min.js:1:47206
    at r (js/vendor/mocha.min.js:1:45957)
    at js/vendor/mocha.min.js:1:46026
    at n (js/vendor/mocha.min.js:1:45394)
    at js/vendor/mocha.min.js:1:45868
    at i (js/vendor/mocha.min.js:1:571)
```
In server/deregistration/Server-Dereg-Req-2.js, `**registrationRequest**` should be `**deregistrationRequest**`. Similar issue exists w.r.t P-1.
```
   it(`P-2     
                
        DeregistrationRequest must contain "authenticators" field, of type SEQUENCE. Authenticators MUST not be empty.
                
    `, () => {
        assert.isArray(**registrationRequest**.authenticators, 'Authenticators MUST be of type SEQUENCE');
        assert.isNotEmpty(**registrationRequest**.authenticators, 'Authenticators MUST NOT be empty!');
```

**Comment by herrjemand** [comment]
Resolved
