### ISSUE TITLE
UAF 1.1 - Server-Dereg-Req-4 P-1  fails in the tool

### ISSUE THREAD

**Issue by vens1** [fido-alliance/conformance-tool-issues#53]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?

Server

## What is the version of the tool are you using?
0.9.18

## Issue description

```
Server-Dereg-Req-4 Test the Authenticator Dictionary
P-1 For each DeregisterAuthenticator in "authenticators" sequence: "aaid" field must be of type DOMString, nine(9) characters long, and it must match /^[0-9A-Fa-f]{4}#[0-9A-Fa-f]{4}$/ regex pattern. ‣
TypeError: Cannot read property 'aaid' of undefined
    at r.it (eval at compileCode (js/sandbox.js:25:26), <anonymous>:5065:101)
    at r (js/vendor/mocha.min.js:1:40757)
    at r.run (js/vendor/mocha.min.js:1:41838)
    at i.runTest (js/vendor/mocha.min.js:1:46569)
    at js/vendor/mocha.min.js:1:47206
    at r (js/vendor/mocha.min.js:1:45957)
    at js/vendor/mocha.min.js:1:46026
    at n (js/vendor/mocha.min.js:1:45394)
    at js/vendor/mocha.min.js:1:45868
    at i (js/vendor/mocha.min.js:1:571)
P-2 For each DeregisterAuthenticator in "authenticators" sequence: "keyID" field must be of type DOMString, and: (a) it must be base64url encoded (b) it must be more than 43 characters(32 bytes) long (c) it must be less than 2731 characters(2048 bytes) long ‣
P-3 Request deregistration for all assertions for a single authenticator specified by an AAID, and check that server returns deregistration request with "DeregisterAuthenticator.aaid" set to specified AAID, and "DeregisterAuthenticator.keyID" set to "empty" DOMString. ‣
SyntaxError: Unexpected token h in JSON at position 39
P-4 Request deregistration for all assertions for all authenticators, and check that server returns DeregistrationRequest with "DeregisterAuthenticator.aaid" and "DeregisterAuthenticator.keyID" set to "empty" DOMString. ‣
SyntaxError: Unexpected token h in JSON at position 39
```

**Comment by herrjemand** [comment]
Resolved
