### ISSUE TITLE
UAF 1.1 - Server-Dereg-Req-4 Tests P-1, P-3 and P-4 fail in the tool

### ISSUE THREAD

**Issue by vens1** [fido-alliance/conformance-tool-issues#55]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?

Server
## What is the version of the tool are you using?
0.9.19

## Issue description

```
Server-Dereg-Req-4 Test the Authenticator Dictionary
P-1 For each DeregisterAuthenticator in "authenticators" sequence: "aaid" field must be of type DOMString, nine(9) characters long, and it must match /^[0-9A-Fa-f]{4}#[0-9A-Fa-f]{4}$/ regex pattern. ‣
TypeError: Cannot read property 'aaid' of undefined
    at r.it (eval at compileCode (js/sandbox.js:25:26), <anonymous>:5335:107)
    at r (js/vendor/mocha.min.js:1:40757)
    at r.run (js/vendor/mocha.min.js:1:41838)
    at i.runTest (js/vendor/mocha.min.js:1:46569)
    at js/vendor/mocha.min.js:1:47206
    at r (js/vendor/mocha.min.js:1:45957)
    at js/vendor/mocha.min.js:1:46026
    at n (js/vendor/mocha.min.js:1:45394)
    at js/vendor/mocha.min.js:1:45868
    at i (js/vendor/mocha.min.js:1:571)
```
```
P-3 Request deregistration for all assertions for a single authenticator specified by an AAID, and check that server returns deregistration request with "DeregisterAuthenticator.aaid" set to specified AAID, and "DeregisterAuthenticator.keyID" set to "empty" DOMString. ‣
TypeError: Cannot create property 'deregisterAAID' on string '{"username":"DbSh5RDU8PgGqer7t1Uu"}'
    at Object.get (eval at compileCode (js/sandbox.js:25:26), <anonymous>:5006:44)
    at rest.register.get.then.then.then (eval at compileCode (js/sandbox.js:25:26), <anonymous>:5372:41)

P-4 Request deregistration for all assertions for all authenticators, and check that server returns DeregistrationRequest with "DeregisterAuthenticator.aaid" and "DeregisterAuthenticator.keyID" set to "empty" DOMString. ‣
TypeError: Cannot create property 'deregisterAll' on string '{"username":"cEZPDE1uwSUGj0N1El2t"}'
    at Object.get (eval at compileCode (js/sandbox.js:25:26), <anonymous>:5009:43)
    at rest.register.get.then.then.then (eval at compileCode (js/sandbox.js:25
```

**Comment by herrjemand** [comment]
Resolved. Newest build should be up in the next few hours
